language: ruby
bundler_args: --without development integration
rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
before_script:
  - bundle exec berks install
script: bundle exec rspec spec
